import type { Metadata } from 'next'
import { Nunito } from 'next/font/google'

import { esES } from '@clerk/localizations'
import { ClerkProvider } from '@clerk/nextjs'

import { Toaster } from '@/components/ui/sonner'

import '@/styles/globals.css'

const nunito = Nunito({
  subsets: ['latin'],
  variable: '--font-noto-sans',
  display: 'swap',
  weight: ['400', '500', '700', '900']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider localization={esES}>
      <html lang='es' suppressHydrationWarning>
        <body className={`${nunito.className} antialiased`}>
          {children}

          <Toaster />
        </body>
      </html>
    </ClerkProvider>
  )
}
